### PR TITLE
Bootstrap breaking changes Fixes.

### LINKED ISSUE #849: Check boostrap breaking changes
There are some breaking changes in Bootstrap v5, and we should check the effect:

- [x] We use card-columns classes, but they have been removed: https://getbootstrap.com/docs/5.3/migration/#card and https://bootstrap-vue-next.github.io/bootstrap-vue-next/docs/migration-guide.html#bcardgroup
- [x] text-muted is deprecated: https://getbootstrap.com/docs/5.3/migration/#utilities-2
- [x] Check media queries: https://getbootstrap.com/docs/5.3/migration/#sass

### PR DESCRIPTION
**Pull request by saidy-moregeo**
## Proposed Changes

Resolve the bootstrap breaking changes.

## Checklist

- [x] Deprecated .text-muted replaced by .text-body-secondary.
- [x] Replace Custom column on validation component with bootstrap grid layout.
- [x] Adjust the media query breakpoint to match with target.

### CODE REVIEW

**Review by m-mohr — CHANGES_REQUESTED** [review]
Columns are not splitting as expected for larger display widths for metadata in the Catalog view.

Same happends with assets, which should stick to one column:

{F5F6C816-1A48-4F51-A532-F71DECC6AEB8}

File: src/views/Catalog.vue [hunk 1]
```diff
@@ -360,7 +360,7 @@ export default defineComponent({
     column-count: 1;
 
     &:not(.count-1) {
-      @include media-breakpoint-up(xxxl) {
+      @include media-breakpoint-up(xl) {
```
Comment (m-mohr) [inline src/views/Catalog.vue]: Didn't you say we only have to change it for "down"? Also, this would jump directly from xxxl to xl, instead of xxl...

File: src/views/Validation.vue [hunk 2]
```diff
@@ -128,15 +133,5 @@ export default defineComponent({
...
-  }
-  @include media-breakpoint-up(lg) {
-    column-count: 3;
-  }
-  @include media-breakpoint-up(xxxl) {
-    column-count: 4;
-  }
-}
+
 </style>
```
Comment (m-mohr) [inline src/views/Validation.vue]: The shole style section can be removed as there's no specific style for this component left.

File: src/views/Catalog.vue (hunk 1 above)
Comment (saidy-moregeo) [reply src/views/Catalog.vue]: Yes that's an oversight while testing - reverted.

File: src/views/Validation.vue (hunk 2 above)
Comment (saidy-moregeo) [reply src/views/Validation.vue]: Done.

File: src/views/Catalog.vue (hunk 1 above)
Comment (m-mohr) [reply src/views/Catalog.vue]: I still see it, didn't you revert it?

**Review by m-mohr — APPROVED** [review]
